version: '3.7'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/conf.d/certs/
      - ./nginx/conf.d:/etc/nginx/conf.d
    dns_search: example.test